use serde::{Deserialize, Serialize};
use egui::Pos2;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub(crate) enum ComponentKind {
    Resistor,
    Capacitor,
    Inductor,
    Diode,
    Led,
    ZenerDiode,
    Switch,
    PushButton,
    SlideSwitch,
    Ground,
    VSource,
    ISource,
    Battery,
    OpAmp,
    Lamp,
    Potentiometer,
    NpnTransistor,
    PnpTransistor,
    Nmosfet,
    Pmosfet,
    VoltageReg,
    Fuse,
    LogicNot,
    LogicAnd,
    LogicOr,
    LogicNand,
    LogicNor,
    LogicXor,
    Esp32,
    Esp32S3,
    Esp32C3,
    ArduinoUno,
    RaspberryPiPico,
    Breadboard,
    Relay,
    DcMotor,
    Servo,
    Oled,
    Sensor,
    NetLabel,
    Timer555,
    Crystal,
    Transformer,
    Display7Seg,
    Thermistor,
    Varistor,
    VoltageRef,
    MotorDriver,
    SchottkyDiode,
    TvsDiode,
    Phototransistor,
    Optocoupler,
    GenericIc,
}

#[derive(Debug, Clone)]
pub(crate) struct Component {
    pub(crate) id: u64,
    pub(crate) kind: ComponentKind,
    pub(crate) pos: Pos2,
    pub(crate) rotation: i32,
    pub(crate) label: String,
    pub(crate) value: String,
}
